language: generic
sudo: required
services:
- docker
after_success:
  # for local testing, needs to be set on travis, too:
  # export HEROKU_TOKEN=$(heroku auth:token)
- heroku container:login
- heroku container:push web
