language: generic
sudo: required
services:
- docker
after_success:
  # for local testing, needs to be set on travis, too:
  # export HEROKU_TOKEN=$(heroku auth:token)
- echo "$HEROKU_TOKEN" | docker login -u _ registry.heroku.com --password-stdin
- docker build -t registry.heroku.com/gin-web-example/web .
- docker push registry.heroku.com/gin-web-example/web
- heroku run --app gin-web-example
