language: generic
sudo: required
services:
- docker
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
- docker build -f Dockerfile -t registry.heroku.com/gin-web-example/web .
- docker push registry.heroku.com/gin-web-example/web
